### ISSUE TITLE
Write a brief description of what the workshop will be

### ISSUE THREAD

**Issue by NataliaLKB** [gu-lseg/course-outline#2]
This description should be enough for us to communicate to our different community partners what the workshop would be.

This should include:
- [x] learning outcomes
- [x] overall project (end result)
- [x] general structure
- [x] times (when does it start and end each day)

@OliverJAsh and @susiecoleman are responsible for this to get done in time to propose it to the Diversity group in time for the meeting on the 22nd of April.

**Comment by NataliaLKB** [comment]
Can't assign two people so I assigned susie, feel free to switch if you want :)

**Comment by susiecoleman** [comment]
This has been written and passed on to @TormodMacLean for final editing. 
It has now been used to promote the workshop
